### ISSUE TITLE
[request-feature] issued to groq-updated

### ISSUE THREAD

**Issue by jidan24** [cuyuniversity/react-groq#1]
I want to update the project, please assign it to me.

**Comment by will240303** [comment]
assigned to @jidan24

**Comment by will240303** [comment]
Please create a new pull request for the requested component. We’ll review it and merge it if it meets the necessary criteria. Be sure to reference the pull request here. @jidan24

**Comment by will240303** [comment]
where is your pr? mention here!!! @jidan24

**Comment by jidan24** [comment]
Sorry, I'm oversleep at jemblong @will240303.
This is my pr #2
